version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - "../custom_components:/config/custom_components"
      - "./configuration.yaml:/config/configuration.yaml"
      - "./.storage:/config/.storage"
    restart: unless-stopped
    ports:
      - "8123:8123" # This is required as well.
    expose:
      - 8123 # As is this.